#!/bin/bash

# Script para login recomendado
echo "🔐 GUÍA DE LOGIN - Sistema OLT Antel"
echo "===================================="
echo ""
echo "👤 USUARIOS DISPONIBLES:"
echo ""
echo "🥇 USUARIO RECOMENDADO:"
echo "   Username: alito"
echo "   Rol: Administrador Sistema"
echo "   Estado: ✅ Activo"
echo ""
echo "🥈 USUARIO ALTERNATIVO:"
echo "   Username: admin"
echo "   Rol: Administrador"
echo "   Estado: ✅ Activo"
echo ""
echo "🌐 ACCEDER AL SISTEMA:"
echo "   1. Abrir navegador: http://localhost:3000"
echo "   2. Usar username: alito"
echo "   3. Contraseña: [la que configuraste]"
echo ""
echo "🛡️ PROTECCIÓN DE DATOS:"
echo "   ✅ Los usuarios NO se borran con git pull"
echo "   ✅ Script post-git-pull.sh protege automáticamente"
echo "   ✅ Backup y restauración automática"
echo ""
echo "💡 NOTA: Si olvidas la contraseña, puedes usar el script:"
echo "   ./scripts/actualizar-usuario-aser.js"
echo ""
